**NumPy**

In [1]:
import numpy as np #Çok boyutlu dizilerle ve matrislerle çalışmamızı sağlayan kütüphanedir.

In [2]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]) #1x15 lik vektör
array2 = np.array([[1,2,3],[4,5,6]]) #2x3 matris

print(array.shape) #array'ın shape'ine bakılır. #(15,) -> 15e 1lik vektör
print(array2.shape) #(2,3) ->2ye 3lük matris


(15,)
(2, 3)


In [3]:
newArray = array.reshape(3,5) #oluşturulan 15'e 1'lik vektör 3'e 5'lik matrise dönüştürüldü
print(newArray)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [8]:
print("shape: ",newArray.shape) #(3, 5)
print("dimension: ",newArray.ndim) #oluşturulan matrisin boyutuna bakılır.
print("data type: ",newArray.dtype.name) #data type:  int32
#array'in içindeki verilerin datatype'larını öğrenmek için (float,string,integer) bu method kullanılır
print("size: ",newArray.size) #reshape'ten önceki boyutu verilir.(size:  15)                    
print("type",type(newArray))  #type <class 'numpy.ndarray'>

shape:  (3, 5)
dimension:  2
data type:  int32
size:  15
type <class 'numpy.ndarray'>


In [9]:
zeros = np.zeros((4,3))#4 satır 3 sütunluk 0'lardan oluşan array yaratılır.
#bu matris ile memoryde yer ayırtılır, güncelleme yapılmak istendiğinde güncellenir.
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
np.ones((4,3)) # 1'lerden oluşan 4x3'lük bir matris yaratır.

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
arr=np.empty((4,5)) #boş bir array oluşturulur.
print(arr)

[[0.  0.  0.3 1.  0. ]
 [0.  1.  1.  1.  1. ]
 [1.  1.  1.  0.  0. ]
 [1.  0.5 0.  0.  1. ]]


In [17]:
np.arange(3,25,3) #3den başlayıp 21de bitecek şekilde üçer üçer artan array oluşturur

array([ 3,  6,  9, 12, 15, 18, 21, 24])

In [20]:
a = np.linspace(0,5,10) #0 ile 5 arasında 10 tane sayı yazdırır
a

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
#NUMPY BASIC OPERATIONS
a=np.array([2,4,6])
b=np.array([3,6,9])

print(a+b) #[5 10 15]
print(a-b) #[-1 -2 -3]
print(a**2) #[4 16 36]

[ 5 10 15]
[-1 -2 -3]
[ 4 16 36]


In [24]:
liste = [1,2,3,4]
arr = np.array([5,6,7,8]) #array tanımlamak için array'in içine liste yazılır.
print(liste) #liste virgülle ayrılır ->[1, 2, 3, 4]
print(arr)   #array virgülle ayrılmaz ->[5 6 7 8]

[1, 2, 3, 4]
[5 6 7 8]


In [25]:
array = np.array(liste)#listeden array geçilir
print(array)

liste2 = list(array) #arrayden listeye geçilir.
print(liste2)

[1 2 3 4]
[1, 2, 3, 4]


In [26]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [28]:
arr1=a
arr2=a
arr1[0]=5 #bu örnekte a,b,c arraylerinin hepsinin 0. indeksi değişir.
#bunun sebebi np.array memory'de bir değer olarak değil bir alan olarak depolanır.
#a,b,c için memory aynı alan ayrıldığından bir tanesi değiştirilince hepsi değişir.

print(a,arr1,arr2)

[5 2 3] [5 2 3] [5 2 3]


In [35]:
a = np.array([1,2,3])
arrCopy = a.copy() #copy methoduyla memory yeni bir alan tahsis edilir.
                   #böylelikle birinin bir indeksi değişince diğerleri bundan etkilenmez.
print(arrCopy) # --> [1 2 3]

a[0]=7
print(arrCopy) # --> a array'inde yapılan değişiklik arrCopy array'ini etkilemez
               # --> [1 2 3]

[1 2 3]
[1 2 3]


In [36]:
array= np.array([1,2,3,4,5,6,7])
print(array[0:3]) #ilk 3 indeksi yazdırır.

[1 2 3]


In [37]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]]) #3x3'lük array oluşturuldu.
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
a = array.ravel() #ravel methoduyla tek boyutlu hale getirilir.
print(a)

[1 2 3 4 5 6 7 8 9]


In [39]:
array2 = a.reshape(3,3) #tekrardan 3x3'lük array haline getirildi.
                        #reshape ile yapılan değişimler kalıcı değildir. yapılan değişim başka bir değişkene kaydedilmelidir.
print(array2

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
array_transpose = array2.T #array'in transpose'u alınır.
print(array_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [41]:
array1=np.array([[1,2],[3,4],[4,5]])
array1

array([[1, 2],
       [3, 4],
       [4, 5]])

In [46]:
array1.resize((2,3)) #resize ile yapılan boyut değişimleri kalıcıdır, aynı array'in içine kaydeder.
print(array1)

[[1 2 3]
 [4 4 5]]
